# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 6d1dd0ad49c167015743de433c81b79441d6b9d330451496310b8c8b39a01b853c388d19ffd70beca0df8f17381783995af55e130ac569f962ae0c1749180f73

test:
  secret_key_base: 853eb668ecb4144689165017680265fc9e660daed141c51233d6e4391d5443a362aa74506619de2cd8dd592feef185ddb4797990017cf037ee7237d6e63eba51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
